
Number of parameters: 29936966
Traceback (most recent call last):
  File "train.py", line 110, in <module>
    train(args)
  File "/Users/a./fast_mri/utils/learning/train_part.py", line 182, in train
    train_loader = create_data_loaders(data_path=args.data_path_train, args=args, shuffle=True, aug=args.aug)
  File "/Users/a./fast_mri/utils/data/load_data.py", line 80, in create_data_loaders
    data_storage = SliceData(
  File "/Users/a./fast_mri/utils/data/load_data.py", line 18, in __init__
    image_files = list(Path(root / "image").iterdir())
  File "/opt/homebrew/anaconda3/envs/fastmri/lib/python3.8/pathlib.py", line 1122, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/root/Data/train/image'